name: CI-CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22.1'

      - name: Install dependencies
        run: go mod tidy

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...

      - name: Find and stop existing process
        run: |
          PID=$(pgrep -f "make run" || true)
          if [ -n "$PID" ]; then
            echo "Stopping existing process with PID $PID"
            kill $PID
            sleep 2
          else
            echo "No existing process found"
          fi

      - name: Start new process in the background
        run: nohup make run & disown
